spring:
  application:
    name: kafka-stream
  profiles:
    active:
    - local    
---
spring:
  config:
    activate:
      on-profile:
      - local        
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: kafka-stream-app
      