spring:
  application:
    name: kafka-stream-app
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: kafka-stream-app
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      
      